### ISSUE TITLE
Sanitize and test the captured stack.

### ISSUE THREAD

**Issue by SirR4T** [paytm/lgr#6]
Currently, we are highly dependent on the frame number, inside [`_p`](https://github.com/paytm/lgr/blob/master/index.js#L150).

We should strive to remove this dependency, otherwise keeping a track of which frame of the stack should be captured is a headache.

We should also add a test case, which throws an error if indeed the function name wasn't captured correctly.

**Comment by shreyagarwal** [comment]
@SirR4T can you please update the issue. See if makes sense after the refactoring

**Comment by SirR4T** [comment]
Should be fixed by #28

**Comment by shreyagarwal** [comment]
@SirR4T can be closed ?
