### ISSUE TITLE
levels below activated levels should not take so much time/processing

### ISSUE THREAD

**Issue by shreyagarwal** [paytm/lgr#9]
If we are printing huuge number of verbose logs in production with Level set to info , then it should not take so much time. If level is not at par, then the logs should simply be discarded

**Comment by samarthmed** [comment]
The case where this occurred was when we send a massive json into the logger. 
The npmlog does a util.format of the message passed to the logger. The massive json here takes time in a util.format whereas a string will not . 


We have the option of returning from the function before it does the util.format (or for that matter any level of processing) but that requires change in the npmlog repo . We'll have to fork it soon .

**Comment by SirR4T** [comment]
Since this was fixed in [our fork](https://github.com/paytm/npmlog), #11 should fix this. Can you please verify?

**Comment by shreyagarwal** [comment]
Done. Removed log recording functionality in npmlog
